### ISSUE TITLE
Issue with package version sorting when `.bcr.*` versions are involved

### ISSUE THREAD

**Issue by redsun82** [bazel-contrib/bcr-ui#142]
I've noticed that for the [zstd](https://registry.bazel.build/modules/zstd) and the [google test](https://registry.bazel.build/modules/googletest) packages there are `.bcr.1` packages that even though are more recent than the latest version and they presumably fix issues with the bazel central registry patching, they are not shown up as the latest versions nor appear in the correct order in the all versions list.

This has caused a problem specifically with zstd, as the `.bcr.1` version contains [this fix](https://github.com/bazelbuild/bazel-central-registry/pull/1394) without which we could not use that dependency, and it was not at all clear from the start we needed to get that version.

**Comment by hobofan** [comment]
Thanks for bringing this up! At the core this sounds like what has already been discussed in https://github.com/bazel-contrib/bcr-ui/issues/54 and https://github.com/bazel-contrib/bcr-ui/issues/22).

The efforts on that front have become a bit stale on my front, but I'll try to push it forward soon (it's essentially fixed on a technical level, but need to go through some organizational motions so that I don't end up as the single point of failure here).

**Comment by lalten** [comment]
Why does the BCR UI even re-sort the versions? Wouldn't it be enough to go with the order of the version list in metadata.json? (https://github.com/bazel-contrib/bcr-ui/issues/54#issuecomment-1416286960)
